{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-correctr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/correctR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/correctR/correctR_{{ version }}.tar.gz
  sha256: c140e92e2eb437b0aa7e3e324107813570958a27cad8ed7e0866872259e3eb80

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('correctR')"           # [not win]
    - "\"%R%\" -e \"library('correctR')\""  # [win]

about:
  home: https://hendersontrent.github.io/correctR/
  license: MIT
  summary: Calculate a set of corrected test statistics for cases when samples are not independent, such as when classification accuracy values are obtained over resamples or through k-fold cross-validation, as proposed by Nadeau and Bengio (2003) <doi:10.1023/A:1024068626366> and presented in Bouckaert and Frank (2004)
    <doi:10.1007/978-3-540-24775-3_3>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
